"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['bq_t4_look.py']
DATA_FILES = ['bq_t4_sys']
OPTIONS = {'argv_emulation': True, 'iconfile':'bq_t4_sys/Viking.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
